### ISSUE TITLE
singlet Dataset error in notebook Figure2_BetaCells_Correlations_GeneExocytosis

### ISSUE THREAD

**Issue by ybernaerts** [jcamunas/patchseq#1]
I think the indices between the annotation and counts data matrix do not match. So I added a line
`annotation = annotation.set_index('Unnamed: 0')`
before we use
`ds = Dataset(counts_table=CountsTable(test),samplesheet=SampleSheet(annotation))`
that would otherwise produce an error.

I still do not, however, recover the Fig. 2 A of the paper.
Additionally, there seems to be a lot of Nans in the ephys. Is this normal?

Thanks in advance!
![Knipsel](https://user-images.githubusercontent.com/38135126/81398829-3f027100-912a-11ea-844d-7addd62e48d3.PNG)

![Knipsel1](https://user-images.githubusercontent.com/38135126/81398882-58a3b880-912a-11ea-822f-16b1b0bebd9d.PNG)

On another note, I do seem to recover fig. 2 B, which I find curious.

**Comment by jcamunas** [comment]
Hi Yves,

I've been looking into the issue. I updated the metadata table to remove the empty column that causes the indices  mismatch. Thanks for catching that. Ihad to remove some columns from the metadata table before uploading, and when I exported the final csv file I introduced this empty column without noticing.

After fixing this, I could not reproduce your issue with Fig.2A (i obtain the same figure that in the paper). It looks like the numbers in your output figure are scrambled. In other words, your heatmap seems identical to the one in the paper (same clustering and color intensities), but the correlation numbers inside the cells do not agree with the color intensity. For instance the two Na+ parameters are really dark but have a correlation of only 0.77, instead of -0.91 (whereas -0.91 is plotted in Ca2+ entry/Early Ca2+, which has a lighter color). Can you verify that this is correct? I think it would be insightful to print the correlation matrices (`df` and `annot`), before and after reordering and plotting. My guess is that this might due to some difference in the library versions (i used seaborn 0.9.0, scipy 1.1.0, pandas 0.22.0).

The fact that there are lots of NaNs is correct. The table contains many cells for which we did not collect electrophysiology (control samples). You can filter them out by using the column `patched` (Yes/No). Moreover for patched cells ('Yes' cells), sometimes it was not possible to measure all parameters. In notebook 6 there's a panel that shows number of NaNs for different parameters of ephys (copied it below). That's why for certain analysis, some parameters were excluded (e.g. Exocytosis norm Ca2+ and reversal potential).

Cheers. Let me know if you can verify the comments above.

<img width="546" alt="Screen Shot 2020-05-08 at 4 24 40 PM" src="https://user-images.githubusercontent.com/10065683/81458025-47b86e80-914d-11ea-9ee4-560092dadd65.png">
.

**Comment by ybernaerts** [comment]
Hi jcamunas,

Regarding your 1st paragraphe: confirmed, that solved the issue.

Regarding your 2nd paragaphe: indeed, when I print `df` the numbers correspond to those in the paper. I think you are correct in the sense that this might be due to a version mismatch.

Regarding your 3rd paragraphe: thank you! That is very helpful.

Yves
